
def re(msg):
    
    my_list=list(msg)
    for s in range(0,my_list.__len__()):
        if  'a' in my_list[s]:my_list[s]='/'
        elif'b' in my_list[s]:my_list[s]='?'
        elif'c' in my_list[s]:my_list[s]='.'
        elif'd' in my_list[s]:my_list[s]='>'
        elif'e' in my_list[s]:my_list[s]=','
        elif'f' in my_list[s]:my_list[s]='<'
        elif'g' in my_list[s]:my_list[s]='\''
        elif'h' in my_list[s]:my_list[s]='"'
        elif'i' in my_list[s]:my_list[s]=';'
        elif'j' in my_list[s]:my_list[s]=':'
        elif'k' in my_list[s]:my_list[s]='\\'
        elif'l' in my_list[s]:my_list[s]='|'
        elif'm' in my_list[s]:my_list[s]=']'
        elif'n' in my_list[s]:my_list[s]='['
        elif'o' in my_list[s]:my_list[s]='}'
        elif'p' in my_list[s]:my_list[s]='{'
        elif'q' in my_list[s]:my_list[s]='='
        elif'r' in my_list[s]:my_list[s]='+'
        elif's' in my_list[s]:my_list[s]='-'
        elif't' in my_list[s]:my_list[s]='_'
        elif'u' in my_list[s]:my_list[s]='0'
        elif'v' in my_list[s]:my_list[s]=')'
        elif'w' in my_list[s]:my_list[s]='9'
        elif'x' in my_list[s]:my_list[s]='('
        elif'y' in my_list[s]:my_list[s]='8'
        elif'z' in my_list[s]:my_list[s]='*'
        elif'A' in my_list[s]:my_list[s]='7'
        elif'B' in my_list[s]:my_list[s]='&'
        elif'C' in my_list[s]:my_list[s]='6'
        elif'D' in my_list[s]:my_list[s]='^'
        elif'E' in my_list[s]:my_list[s]='5'
        elif'F' in my_list[s]:my_list[s]='%'
        elif'G' in my_list[s]:my_list[s]='4'
        elif'H' in my_list[s]:my_list[s]='$'
        elif'I' in my_list[s]:my_list[s]='3'
        elif'J' in my_list[s]:my_list[s]='#'
        elif'K' in my_list[s]:my_list[s]='2'
        elif'L' in my_list[s]:my_list[s]='@'
        elif'M' in my_list[s]:my_list[s]='1'
        elif'N' in my_list[s]:my_list[s]='!'
        elif'O' in my_list[s]:my_list[s]='`'
        elif'P' in my_list[s]:my_list[s]='~'
        elif'Q' in my_list[s]:my_list[s]='あ'
        elif'R' in my_list[s]:my_list[s]='い'
        elif'S' in my_list[s]:my_list[s]='う'
        elif'T' in my_list[s]:my_list[s]='え'
        elif'U' in my_list[s]:my_list[s]='お'
        elif'V' in my_list[s]:my_list[s]='か'
        elif'W' in my_list[s]:my_list[s]='き'
        elif'X' in my_list[s]:my_list[s]='く'
        elif'Y' in my_list[s]:my_list[s]='け'
        elif'Z' in my_list[s]:my_list[s]='こ'
        elif'1' in my_list[s]:my_list[s]='Á'
        elif'2' in my_list[s]:my_list[s]='©'
        elif'3' in my_list[s]:my_list[s]='Ð'
        elif'4' in my_list[s]:my_list[s]='É'
        elif'5' in my_list[s]:my_list[s]='Í'
        elif'6' in my_list[s]:my_list[s]='Ø'
        elif'7' in my_list[s]:my_list[s]='µ'
        elif'8' in my_list[s]:my_list[s]='Ñ'
        elif'9' in my_list[s]:my_list[s]='Ó'
        elif'0' in my_list[s]:my_list[s]='Ö'
        elif' ' in my_list[s]:my_list[s]='Ä'
        elif'`' in my_list[s]:my_list[s]='®'
        elif'~' in my_list[s]:my_list[s]='ß'
        elif'!' in my_list[s]:my_list[s]='Þ'
        elif'@' in my_list[s]:my_list[s]='Ú'
        elif'#' in my_list[s]:my_list[s]='Å'
        elif'$' in my_list[s]:my_list[s]='Ü'
        elif'%' in my_list[s]:my_list[s]='Æ'
        elif'^' in my_list[s]:my_list[s]='á'
        elif'&' in my_list[s]:my_list[s]='ð'
        elif'*' in my_list[s]:my_list[s]='é'
        elif'(' in my_list[s]:my_list[s]='í'
        elif')' in my_list[s]:my_list[s]='ø'
        elif'-' in my_list[s]:my_list[s]='ñ'
        elif'_' in my_list[s]:my_list[s]='ó'
        elif'=' in my_list[s]:my_list[s]='ö'
        elif'+' in my_list[s]:my_list[s]='ä'
        elif'[' in my_list[s]:my_list[s]='þ'
        elif']' in my_list[s]:my_list[s]='ú'
        elif'{' in my_list[s]:my_list[s]='å'
        elif'}' in my_list[s]:my_list[s]='ü'
        elif'\\' in my_list[s]:my_list[s]='æ'
        elif'|' in my_list[s]:my_list[s]='a'
        elif';' in my_list[s]:my_list[s]='b'
        elif':' in my_list[s]:my_list[s]='c'
        elif'\'' in my_list[s]:my_list[s]='d'
        elif'"' in my_list[s]:my_list[s]='e'
        elif',' in my_list[s]:my_list[s]='f'
        elif'.' in my_list[s]:my_list[s]='g'
        elif'<' in my_list[s]:my_list[s]='h'
        elif'>' in my_list[s]:my_list[s]='i'
        elif'/' in my_list[s]:my_list[s]='j'
        elif'?' in my_list[s]:my_list[s]='k'
        elif'©' in my_list[s]:my_list[s]='l'
    
    


    my_string=''.join(my_list)
    return my_string

print(re(input('Enter the string: ')))
